// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	forward "github.com/slok/alertgram/internal/forward"
	mock "github.com/stretchr/testify/mock"

	model "github.com/slok/alertgram/internal/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Forward provides a mock function with given fields: ctx, props, alertGroup
func (_m *Service) Forward(ctx context.Context, props forward.Properties, alertGroup *model.AlertGroup) error {
	ret := _m.Called(ctx, props, alertGroup)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, forward.Properties, *model.AlertGroup) error); ok {
		r0 = rf(ctx, props, alertGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
